var Common = require("Common");
var HomePage = Aliases.flydubai_DCS_UI.HwndSource_DCSMainWindow.DCSMainWindow;

function AddBaggage(Pieces,Weight){
          Common.SafeSetText(HomePage.ContentGrid.WPFObject("ModuleContent").WPFObject("CheckinMainView", "", 1).WPFObject("Grid", "", 1).WPFObject("Grid", "", 1).WPFObject("CheckinMainViewContent").WPFObject("TopWindow").WPFObject("Grid", "", 1).WPFObject("Grid", "", 1).WPFObject("Grid", "", 1).WPFObject("basicTabsContent").WPFObject("BasicTab").WPFObject("Grid", "", 1).WPFObject("tab").WPFObject("BaggaeUserControl").WPFObject("Grid", "", 1).WPFObject("Grid", "", 1).WPFObject("ParentScroll").WPFObject("StackPanel", "", 1).WPFObject("Grid", "", 1).WPFObject("Grid", "", 1).WPFObject("Grid", "", 2).WPFObject("Grid", "", 1).WPFObject("Grid", "", 1).WPFObject("WrapPanel", "", 1).WPFObject("StackPanel", "", 2).WPFObject("txtPieces"),10,Pieces);
          Common.SafeSetText(HomePage.ContentGrid.WPFObject("ModuleContent").WPFObject("CheckinMainView", "", 1).WPFObject("Grid", "", 1).WPFObject("Grid", "", 1).WPFObject("CheckinMainViewContent").WPFObject("TopWindow").WPFObject("Grid", "", 1).WPFObject("Grid", "", 1).WPFObject("Grid", "", 1).WPFObject("basicTabsContent").WPFObject("BasicTab").WPFObject("Grid", "", 1).WPFObject("tab").WPFObject("BaggaeUserControl").WPFObject("Grid", "", 1).WPFObject("Grid", "", 1).WPFObject("ParentScroll").WPFObject("StackPanel", "", 1).WPFObject("Grid", "", 1).WPFObject("Grid", "", 1).WPFObject("Grid", "", 2).WPFObject("Grid", "", 1).WPFObject("Grid", "", 1).WPFObject("WrapPanel", "", 1).WPFObject("StackPanel", "", 4).WPFObject("txtWeight"),10,Weight);
          Common.SafeClickObject(HomePage.ContentGrid.WPFObject("ModuleContent").WPFObject("CheckinMainView", "", 1).WPFObject("Grid", "", 1).WPFObject("Grid", "", 1).WPFObject("CheckinMainViewContent").WPFObject("TopWindow").WPFObject("Grid", "", 1).WPFObject("Grid", "", 1).WPFObject("Grid", "", 1).WPFObject("basicTabsContent").WPFObject("BasicTab").WPFObject("Grid", "", 1).WPFObject("tab").WPFObject("BaggaeUserControl").WPFObject("Grid", "", 1).WPFObject("Grid", "", 1).WPFObject("ParentScroll").WPFObject("StackPanel", "", 1).WPFObject("Grid", "", 1).WPFObject("Grid", "", 1).WPFObject("Grid", "", 2).WPFObject("Grid", "", 1).WPFObject("Grid", "", 1).WPFObject("WrapPanel", "", 1).WPFObject("StackPanel", "", 7).WPFObject("StackPanel", "", 1).WPFObject("btnAddCategory"), 4);
          aqUtils.Delay(3000);
          AddTag('FZ123459');
}

function AddTag(TagNum){
          Common.SafeClickObject(HomePage.ContentGrid.WPFObject("ModuleContent").WPFObject("CheckinMainView", "", 1).WPFObject("Grid", "", 1).WPFObject("Grid", "", 1).WPFObject("CheckinMainViewContent").WPFObject("TopWindow").WPFObject("Grid", "", 1).WPFObject("Grid", "", 1).WPFObject("Grid", "", 1).WPFObject("basicTabsContent").WPFObject("BasicTab").WPFObject("Grid", "", 1).WPFObject("tab").WPFObject("BaggaeUserControl").WPFObject("Grid", "", 1).WPFObject("Grid", "", 1).WPFObject("ParentScroll").WPFObject("StackPanel", "", 1).WPFObject("Grid", "", 1).WPFObject("Grid", "", 1).WPFObject("Grid", "", 2).WPFObject("Grid", "", 1).WPFObject("Grid", "", 2).WPFObject("StackPanel", "", 1).WPFObject("Grid", "", 1).WPFObject("checkboxAddTags"),5);
          aqUtils.Delay(2000);
          Common.SafeSetText(HomePage.ContentGrid.WPFObject("ModuleContent").WPFObject("CheckinMainView", "", 1).WPFObject("Grid", "", 1).WPFObject("Grid", "", 1).WPFObject("CheckinMainViewContent").WPFObject("TopWindow").WPFObject("Grid", "", 1).WPFObject("Grid", "", 1).WPFObject("Grid", "", 1).WPFObject("basicTabsContent").WPFObject("BasicTab").WPFObject("Grid", "", 1).WPFObject("tab").WPFObject("BaggaeUserControl").WPFObject("Grid", "", 1).WPFObject("Grid", "", 1).WPFObject("ParentScroll").WPFObject("StackPanel", "", 1).WPFObject("Grid", "", 1).WPFObject("Grid", "", 1).WPFObject("Grid", "", 2).WPFObject("Grid", "", 1).WPFObject("Grid", "", 2).WPFObject("StackPanel", "", 1).WPFObject("Grid", "", 1).WPFObject("StackPanel", "", 1).WPFObject("tagNumber"),5,TagNum);
          Sys.Desktop.Keys("[Tab]");
          aqUtils.Delay(1000);          
          Common.SafeClickObject(HomePage.ContentGrid.WPFObject("ModuleContent").WPFObject("CheckinMainView", "", 1).WPFObject("Grid", "", 1).WPFObject("Grid", "", 1).WPFObject("CheckinMainViewContent").WPFObject("TopWindow").WPFObject("Grid", "", 1).WPFObject("Grid", "", 1).WPFObject("Grid", "", 1).WPFObject("basicTabsContent").WPFObject("BasicTab").WPFObject("Grid", "", 1).WPFObject("tab").WPFObject("BaggaeUserControl").WPFObject("Grid", "", 1).WPFObject("Grid", "", 1).WPFObject("ParentScroll").WPFObject("StackPanel", "", 1).WPFObject("Grid", "", 1).WPFObject("Grid", "", 1).WPFObject("Grid", "", 2).WPFObject("Grid", "", 1).WPFObject("Grid", "", 2).WPFObject("StackPanel", "", 1).WPFObject("Grid", "", 1).WPFObject("StackPanel", "", 3).WPFObject("StackPanel", "", 1).WPFObject("Button", "Add", 1),5);
          aqUtils.Delay(3000);
}

module.exports.AddBaggage = AddBaggage;
module.exports.AddTag = AddTag;